name: Hardhat CI
on: [push]

jobs:
  test:
    name: Hardhat unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install
        working-directory: ./migration

      - name: Run XDEFI to CTRL migration test on hardhat
        run: npx hardhat test test/XdefiToCtrlMigration.ts --network hardhat
        working-directory: ./migration

      - name: Run CTRL to XDEFI migration test coverage on hardhat
        run: npx hardhat coverage --sources XdefiToCtrlMigration.sol
        working-directory: ./migration

      - name: Update README.md
        run: |
          npm install -g markdown-include
          markdown-include markdown.json
        working-directory: ./migration

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Hardhat CI
          message: Update README.md
          add: README.md
          push: true
        run: "echo 'Changes committed and pushed'"
        working-directory: ./migration

    env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        BOB_PRIVATE_KEY: ${{ secrets.BOB_PRIVATE_KEY }}
        ALICE_PRIVATE_KEY: ${{ secrets.ALICE_PRIVATE_KEY }}

        SEPOLIA_API: ${{ secrets.SEPOLIA_API }}
        ETHEREUM_API: ${{ secrets.ETHEREUM_API }}

        REPORT_GAS: true
        SOLIDITY_COVERAGE: true
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



